/* AppHub.Studio — единый источник правды для карты экосистемы · v2 (актуализация 2026-09-14).
   Меняй данные здесь, затем: python3 src/build.py  →  v2/index.html + AppHub-карта-экосистемы.html
   status (s): "live" — в проде | "dev" — в разработке / прототип / демо | "concept" — концепт | "core" — слой/ядро
   type (t):   "hub" — слой петли | "mini" — продукт/направление | "case" — живой кейс из портфолио (клиентское приложение)
   pf: slug в портфолио-боте (t.me/Portfolio_AppHub_Bot) — по нему подтягиваются экраны из галереи; screens — сколько экранов там лежит.
   Источники: _DISTRIBUTION_KIT/05_Portfolio/PORTFOLIO.md (34 продукта · 205 экранов · 16 ниш), LINKS.md, NOTEBOOK_Презентация/*.md */
window.APPHUB_DATA = {
  viewBox: "-80 -50 2020 950",
  meta: { updated: "2026-09-14", portfolio: 34, screens: 205, niches: 16, portfolioUrl: "https://t.me/Portfolio_AppHub_Bot", galleryBase: "https://apphub-portfolio-livid.vercel.app/gallery/",
    social: [
      {k:"tg",label:"Telegram",url:"https://t.me/AppHub_Studio"},
      {k:"ig",label:"Instagram",url:"https://www.instagram.com/apphubstudio/"},
      {k:"x",label:"X",url:"https://x.com/Apphubstudio"},
      {k:"in",label:"LinkedIn",url:"https://www.linkedin.com/company/apphubstudio/"},
      {k:"ph",label:"Product Hunt",url:"https://www.producthunt.com/@apphubstudio"},
      {k:"web",label:"apphub.studio",url:"https://apphub.studio"}
    ] },
  nodes: {
    /* ——— APPHUB STUDIO · вход в экосистему ——— */
    site:{t:"mini",layer:"ROOT",s:"live",x:120,y:44,label:"Сайт",cat:"Студия · apphub.studio",desc:"Главный вход: «приложение без установки». Конструктор из 5 шагов, программа Loop, оффер Founding Partners (до 1 января 2027), кейсы и контакты. Сайт отвечает и ИИ-агентам — есть llms.txt.",inter:"Заявка с сайта уходит в Studio Bot. Конструктор ведёт в OS Builder и к ручной сборке студией. Со страницы Loop — в сеть лояльности.",imgs:["/v2/shots/site-1.jpg","/v2/shots/osb-1.jpg","/v2/shots/osb-2.jpg","/v2/shots/site-2.jpg","/v2/shots/site-3.jpg"],links:[{label:"apphub.studio",url:"https://apphub.studio"},{label:"Конструктор · 5 шагов",url:"https://apphub.studio/constructor"},{label:"Founding Partners",url:"https://apphub.studio/founders"}]},
    studiobot:{t:"mini",layer:"ROOT",s:"live",x:262,y:44,label:"Studio Bot",cat:"Студия · родитель всех ботов",desc:"@AppHub_Studio_Bot — витрина студии в Telegram (Taplink): продукты и кейсы одним касанием, контакты фаундеров, репост страницы, оффер ИИ-маркетолога. Родитель всей семьи ботов: демо Dine, Neko, Batumi живут внутри него.",inter:"Принимает заявки с сайта и конструктора; запускает демо L3-приложений; отсюда рождаются продукт-боты (LinkOS, OS Builder) и юзер-боты клиентов.",pf:"taplink",screens:5,links:[{label:"@AppHub_Studio_Bot",url:"https://t.me/AppHub_Studio_Bot"},{label:"Поддержка",url:"https://t.me/AppHub_Support"}]},
    portfolio:{t:"mini",layer:"ROOT",s:"live",x:404,y:44,label:"Портфолио",cat:"Студия · 34 продукта · 205 экранов",desc:"Портфолио-бот: 34 карточки, 205 реальных экранов, поиск, фильтры по 16 нишам, лайтбокс с подписью к каждому экрану, два языка. Счётчики считаются из данных — разойтись с реальностью не могут. Веб-зеркало для тех, кто вне Telegram.",inter:"Это «папка с наработками», когда её просят ссылкой. Каждый кейс справа на этой карте ведёт в него. Питает продажи студии и конструктор.",imgs:["/v2/shots/portfolio-1.jpg","/v2/shots/portfolio-2.jpg","/v2/shots/portfolio-3.jpg"],links:[{label:"@Portfolio_AppHub_Bot",url:"https://t.me/Portfolio_AppHub_Bot"},{label:"Веб-зеркало",url:"https://apphub-portfolio-livid.vercel.app"}]},
    linkos:{t:"mini",layer:"ROOT",s:"live",x:190,y:98,label:"LinkOS",cat:"Студия · ступень 1 · визитка",desc:"Конструктор цифровых визиток внутри Telegram: блоки, темы, публикация за Stars, личный кабинет, редактор QR-кода. Первая ступень воронки: free → PRO.",inter:"Вход в экосистему для малого бизнеса. Апселлит OS Builder (ступень 2) и кастом студии (ступень 3). Механика конструктора наследуется в OS Builder один-в-один.",pf:"linkos",screens:13,links:[{label:"@Linkos_AppHub_bot",url:"https://t.me/Linkos_AppHub_bot"}]},
    osbuilder:{t:"mini",layer:"ROOT",s:"dev",x:335,y:98,label:"OS Builder",cat:"Студия · ступень 2 · конструктор приложений",desc:"AppHUB OS Builder — конструктор Telegram Mini App под нишу: 20 шаблонов (бьюти, кафе, медицина, магазин, фитнес, ивенты, недвижимость, аренда, крипто, город, ЖКХ…), редактор блоков и бренда, умные модули (запись, push, Loop), автозаполнение из Telegram, magic-импорт бренда с сайта или Instagram за 30 секунд. Публикация в бот клиента и оплата — на подключении бэкенда.",inter:"Собирает L3-приложения из ДНК доноров (Dine, CityHub, Zem Doc, AllTrust…) без участия студии — философия 95/5. Каждый собранный бот автоматически встаёт в сеть Loop.",pf:"apphub-os",screens:10,links:[{label:"apphub-os.vercel.app",url:"https://apphub-os.vercel.app"}]},

    /* ——— ПЕТЛЯ · ядро ——— */
    l1:{t:"hub",layer:"L1",s:"core",x:180,y:400,w:232,h:108,label:"L1 · USERS / AGENTS",sub:"Пользователи и их ИИ-агенты",cat:"L1 · точка входа",desc:"Пользователь уже залогинен в мессенджере: ноль установок, паролей и сторов. Рядом — его ИИ-агент, который сам находит предложения и готовит действие, человеку остаётся подтвердить и оплатить. Заявлено публично: приложения студии взаимодействуют с ИИ-агентами других моделей; машиночитаемый слой — в roadmap.",inter:"Ассистент идёт к L2-агрегаторам и напрямую в L3-бизнесы. Loop-баллы, заработанные в одном приложении, тратит в любом другом — это и возвращает его в петлю.",link:null},
    l2:{t:"hub",layer:"L2",s:"core",x:625,y:400,w:164,h:104,label:"L2 · АГРЕГАТОРЫ",sub:"Подборки сервисов",cat:"L2 · ядро петли",desc:"Агрегаторы: подборки и каталоги сервисов под нишу или город (CityHub, Neon, BazApp, Korobka). Возможны white-label-версии каждого.",inter:"Принимают запрос ассистента L1, подбирают L3-бизнесы, собирают предложение и раздают трафик вниз по петле.",link:null},
    l3:{t:"hub",layer:"L3",s:"core",x:1190,y:400,w:160,h:104,label:"L3 · БИЗНЕСЫ",sub:"Приложения бизнесов",cat:"L3 · продукты бизнесов",desc:"Приложения конкретных бизнесов — меню, бронь, запись, оплата, лояльность. Каждый проект — два приложения: клиентское и админ-панель. Собираются студией за 1–3 дня или через OS Builder. Справа — 17 живых кейсов из портфолио.",inter:"Принимают заказ из петли и от утилит; через Loop возвращают гостя в L1 и передают соседним бизнесам сети. Общаются между собой через ботов.",link:null},
    loop:{t:"mini",layer:"NET",s:"dev",x:685,y:690,label:"LOOP · сеть лояльности",cat:"Протокол · ступень 3 · то, ради чего всё",desc:"Loop — единая валюта сети: 1–5% от покупки возвращается клиенту Loop-баллами, которые он тратит в любом приложении сети. Партнёры получают cross-traffic и готовую лояльность без рекламных бюджетов. Взнос бизнеса идёт в общий призовой фонд с публичным ежемесячным розыгрышем в Батуми. Механика встроена в часть приложений; единый реестр начислений с выпиской бизнесу — следующий шаг (оценка полгода).",inter:"Замыкает петлю L3 → L1: гость одного бизнеса приносит выручку другому. Граф связей между бизнесами — то, чего нет ни у одного конкурента с «отдельной TMA». Сверху подключаются CityHub, EPOCH, Dine, Car Rent.",imgs:["/v2/shots/loop-1.jpg","/v2/shots/loop-2.jpg","/v2/shots/loop-3.jpg"],links:[{label:"apphub.studio/loop",url:"https://apphub.studio/loop"}]},

    /* ——— L2 · агрегаторы ——— */
    wwc:{t:"mini",layer:"L2",s:"dev",dom:"Еда",x:470,y:282,label:"WWC",cat:"L2 · кулинария",desc:"What We Cook — кулинарные поединки и рейтинги лучших рецептов. Родственник Dolce Eda (повара, книга рецептов, челленджи).",inter:"Совместно редактируемые списки продуктов → Shops; рецепты → заказ блюд в Dine и Dolce Eda.",link:null},
    bazapp:{t:"mini",layer:"L2",s:"dev",dom:"Ритейл",x:470,y:400,label:"BazApp",cat:"L2 · P2P-маркетплейс",desc:"P2P-маркетплейс в Telegram: объявления по категориям, защита от скама, AI Deal Room для разрешения споров, рейтинг продавцов.",inter:"Сводит покупателей и продавцов; заказы → Shops, оплата — Crypto. Принимает пользователей из L1.",link:null},
    korobka:{t:"mini",layer:"L2",s:"dev",dom:"Недвижимость",x:470,y:518,label:"Korob·ka",cat:"L2 · калькуляторы подрядчика",desc:"Калькуляторы подрядчика: кладка и перегородки по RDS 82-202-96, смета материалов с запасом на подрезку, ИИ-прораб, история заказов, голосование за следующий калькулятор. Три языка. В портфолио — прототип.",inter:"Магнит-утилита для стройки: ведёт в Shops (стройматериалы), к Realty и Стройке; крупные расчёты — через Crypto.",pf:"korobka",screens:8,links:[{label:"korob-ka.vercel.app",url:"https://korob-ka.vercel.app"}]},
    cityhub:{t:"mini",layer:"L2",s:"live",dom:"Батуми",x:790,y:270,label:"CityHub",cat:"L2 · городской гид",desc:"«Куда пойти сейчас»: места рядом на карте, события, ниши и категории, профиль с баллами Loop. Умный городской консьерж с ИИ-рекомендациями, квестами и стриками.",inter:"Распределяет трафик в Dine, Events, Tours, CarRent, Shops, Дом и ЖКХ; первый носитель Loop в городе.",pf:"cityhub",screens:4,links:[{label:"Открыть CityHUB",url:"https://masteroch.github.io/cityhub/"}]},
    neon:{t:"mini",layer:"L2",s:"live",dom:"Батуми",x:800,y:400,label:"Neon",cat:"L2 · Батуми",desc:"Batumi Neon — городской и развлекательный агрегатор Батуми: ночная жизнь, вечеринки, автопарк. Донор дизайна для Car Rent.",inter:"Ведёт в Events, Tours, CarRent, Dine; ИИ-консьерж NEON AI.",imgs:["/v2/shots/neon-1.jpg","/v2/shots/neon-2.jpg","/v2/shots/neon-3.jpg"],links:[{label:"@BatumiNeonBot",url:"https://t.me/BatumiNeonBot"}]},
    batumito:{t:"mini",layer:"L2",s:"dev",dom:"Батуми",x:790,y:530,label:"Batumito",cat:"L2 · Батуми",desc:"Батумский агрегатор: доставка на пляж, городские события, ночная жизнь, дорогие машины, приватные пати. Из той же серии, что Neon.",inter:"Ведёт в Tours, CarRent, Dine, Shops, Events; логистика — Dropper.",link:null},
    realestate:{t:"mini",layer:"L2",s:"dev",dom:"Недвижимость",x:625,y:538,label:"Realty",cat:"L2 · недвижимость",pf:"realty-preset",desc:"Агрегатор недвижимости: подборки объектов и застройщиков. Кейсы уже есть — Realty Preset и Alliance Centropolis продают новостройки прямо в Telegram.",inter:"Замыкается на Korobka и Стройку; ведёт к застройщикам (Realty Preset, Alliance), в Tours и Events (Realty Forum); крупные расчёты — через Crypto.",link:null},

    /* ——— L3 · направления бизнесов ——— */
    crypto:{t:"mini",layer:"L3",s:"live",dom:"Недвижимость",x:1030,y:272,label:"Crypto",cat:"L3 · финтех",desc:"AllTrust.me — крипто-обменник: KYC, лояльность, снятие наличных. Под крупные покупки — недвижимость, ремонт, стройматериалы. Антифрод-опыт отсюда переиспользуется в Loop.",inter:"Завести деньги в крипту и снять кэш на дорогую покупку. Связан с Korobka, Стройкой, Realty, BazApp.",imgs:["/v2/shots/crypto-1.jpg"],links:[{label:"@AllTrustMe_robot",url:"https://t.me/AllTrustMe_robot/app"},{label:"alltrustme.vercel.app",url:"https://alltrustme.vercel.app"}]},
    events:{t:"mini",layer:"L3",s:"live",dom:"Туризм",x:1190,y:255,label:"Events",cat:"L3 · события",pf:"ebit",desc:"Событийные приложения: форумы, выставки, конференции, фестивали. Живые кейсы — EBIT Batumi Expo 2026 (4000+ гостей, ИИ-гид) и Realty Forum 2026 (QR-бейджи, B2B-мэтчинг).",inter:"Принимает из CityHub, Neon, Batumito; связан со Stage и Tours; переводит трафик в Dine — на рестораны и кафе.",subs:[{label:"Экспо",x:1030,y:178},{label:"Конференции",x:1190,y:178},{label:"Фестивали",x:1360,y:178}],links:[{label:"EBIT Expo 2026",url:"https://t.me/expobatumibot/EBIT2026?startapp=home"},{label:"Realty Forum 2026",url:"https://realty-forum-tma.vercel.app"}]},
    stage:{t:"mini",layer:"L3",s:"concept",dom:"Туризм",x:1340,y:282,label:"Stage",cat:"L3 · организаторы (рабочее имя)",desc:"Для организаторов концертов и событий: продажа билетов, контакты специалистов, проходки.",inter:"Связан с Events; контент — MusicHAEd.",link:null},
    med:{t:"mini",layer:"L3",s:"live",dom:"Здоровье",x:1470,y:210,label:"Клиники",cat:"L3 · медицина",pf:"antiage",desc:"Медцентры и клиники: запись к врачу с выбором времени, прайс, специалисты, результаты до/после, ИИ-регистратура. Живые кейсы — Земский Доктор (dr.Zem) и AntiAge (344 позиции прайса, кабинет клиники).",inter:"Трафик из CityHub; лояльность через Loop; контент — LeadOS. Соседи — ANZH и фитнес.",link:null},
    carrent:{t:"mini",layer:"L3",s:"live",dom:"Туризм",x:1030,y:400,label:"Car Rent",cat:"L3 · автопрокат",desc:"Аренда авто: каталог, бронь с оплатой (Wallet или Stars), клуб со статусами, рефералка, ИИ-консьерж. Живые кейсы — LiteRent и Batumi Neon.",inter:"Для туризма — Neon, Batumito, Tours, CityHub. Loop встроен.",pf:"batumi-neon",screens:7,links:[{label:"LiteRent",url:"https://t.me/LiteRent_robot/app"},{label:"Batumi Neon",url:"https://t.me/BatumiNeonBot"}]},
    tours:{t:"mini",layer:"L3",s:"live",dom:"Туризм",x:1340,y:522,label:"Tours",cat:"L3 · туры",pf:"paratravel-club",desc:"Туры и экскурсии. Живой кейс — Paratravel Club: подбор туров за 4 вопроса, консьерж, клуб с кэшбэком, trip-companion и админка с ИИ-сводкой.",inter:"Связаны с Neon, Batumito, CityHub, CarRent, Dine, Events.",subs:[{label:"Экскурсии",x:1150,y:610},{label:"Медицинские",x:1308,y:610},{label:"Спортивные",x:1230,y:682}],links:[{label:"Paratravel Club",url:"https://paratravel-club.vercel.app"}]},
    dine:{t:"mini",layer:"L3",s:"live",dom:"Еда",x:1190,y:542,label:"Dine",cat:"L3 · HoReCa · шаблон-донор",desc:"Ресторанное приложение и шаблон для HoReCa: меню с фото, корзина, бронь стола, лиги гостей, бонусы. Плюс админка ресторатора: меню, заказы, брони, аналитика зала. Донор для EPOCH, Neko Sushi, Dolce Eda.",inter:"Трафик из WWC, CityHub, Batumito, Neon; игры для гостей — Crooked Cook; доставка — Dropper; контент — LeadOS.",subs:[{label:"Рестораны",x:1035,y:612},{label:"Бары",x:1190,y:612},{label:"Кафе",x:1345,y:612},{label:"Отели",x:1041,y:680},{label:"Бьюти",x:1190,y:680},{label:"Доставка",x:1339,y:680}],pf:"dine",screens:6,admin:{label:"Админка ресторатора",url:"https://t.me/AppHub_Studio_Bot/Dine_admin?startapp=demo",pf:"dine-admin",screens:4},links:[{label:"Демо клиента",url:"https://t.me/AppHub_Studio_Bot/dine?startapp=demo"}]},
    shops:{t:"mini",layer:"L3",s:"live",dom:"Ритейл",x:1030,y:525,label:"Shops",cat:"L3 · ритейл",pf:"tds-mebel",desc:"Магазины и ритейл: каталог, корзина, оплата, клуб. Живой кейс — ТДС Мебель: кухня по фото комнаты, каталог на 3 201 позицию, цех раскроя в админке.",inter:"Заказы из WWC, CityHub, Batumito, Korobka, BazApp; логистика — Dropper.",subs:[{label:"Продукты",x:875,y:610},{label:"Одежда",x:990,y:610},{label:"Зоо",x:1105,y:610},{label:"Стройматериалы",x:925,y:680},{label:"Техника",x:1070,y:680}],links:[{label:"ТДС Мебель",url:"https://tds-mebel.vercel.app"}]},
    construction:{t:"mini",layer:"L3",s:"live",dom:"Недвижимость",x:1370,y:408,label:"Стройка",cat:"L3 · застройщики и услуги",pf:"realty-preset",desc:"Застройщики, бригады, прорабы, дизайнеры. Живые кейсы — Realty Preset (3D-шахматка дома, статусы квартир, ход стройки) и Alliance Centropolis (планировки, инвест-условия).",inter:"Магазины (Shops) и строительные услуги; замыкается на Korobka и Realty; крипто-обменник — за снятием наличных.",subs:[{label:"Застройщики",x:1462,y:340},{label:"Бригады",x:1487,y:386},{label:"Прорабы",x:1487,y:432},{label:"Дизайнеры",x:1462,y:478}],link:null},
    anzh:{t:"mini",layer:"L3",s:"live",dom:"Здоровье",x:1455,y:512,label:"ANZH",cat:"L3 · бьюти",desc:"ANZH.store — бьюти-экосистема в Telegram (клиент + админка): ИИ-маскот, диагностика кожи, запись на процедуры, программа лояльности. Рядом — ANZH Skin Intelligence (6 тестов → Skin Passport) и прототип приложения бьюти-мастера.",inter:"Трафик из CityHub, Neon; оплата — Crypto; контент — LeadOS; лояльность — Loop.",pf:"beauty-tma",screens:5,links:[{label:"anzh.store",url:"https://anzh.store"},{label:"@ANZH_studio_bot",url:"https://t.me/ANZH_studio_bot"}]},
    kingfit:{t:"mini",layer:"L3",s:"dev",dom:"Здоровье",x:1465,y:300,label:"KING Fit",cat:"L3 · фитнес",desc:"Фитнес-трекер с ИИ-тренером для залов и персональных тренеров: план дня, тренировки по подходам, питание и рекорды. Демо. Родственник — Mega Gym Batumi (клубная карта с QR, 25 тренеров).",inter:"Привлекает пользователей L1; связан с CityHub и спортивными турами Tours; оплата — Crypto.",pf:"king-fit",screens:7,links:[{label:"king-fit.vercel.app",url:"https://king-fit.vercel.app"}]},
    dropper:{t:"mini",layer:"L3",s:"dev",dom:"Еда",x:1490,y:440,label:"Dropper",cat:"L3 · доставка (роботы)",desc:"Доставка роботами в Батуми: еда и товары от кафе и магазинов прямо к клиенту на пляж, в парк или офис. B2B-SaaS для заведений.",inter:"Логистика для Dine и Shops; трафик из CityHub, Neon, Batumito.",link:null},
    cityhome:{t:"mini",layer:"L3",s:"live",dom:"Город и дом",x:1480,y:600,label:"Дом и ЖКХ",cat:"L3 · городские сервисы",pf:"almare",desc:"Приложения дома и города: показания счётчиков, платежи и квитанции, заявки с фото и статусом работ, голосования, чат дома, ИИ-консьерж. Живые кейсы — AL MARE Batumi (217 соседей, консьерж «Альма») и Водоканал.",inter:"Трафик из CityHub; сервисы дома → Shops и Стройка; лояльность — Loop.",link:null},

    /* ——— UTILITIES · вне петли · трафик ——— */
    editcmd:{t:"mini",layer:"UT",s:"concept",x:1058,y:44,label:"Edit Cmd",cat:"Утилита · вне петли",desc:"Edit Commander — бесплатный пакетный редактор (PDF, HTML). Вводный продукт с нашей рекламой.",inter:"Реклама приводит трафик в петлю; уникализирует апки. Связан с L3 и Dine.",link:null},
    leados:{t:"mini",layer:"UT",s:"concept",x:1206,y:44,label:"LeadOS",cat:"Утилита · вне петли",desc:"Генерация контента для соцсетей: посты в Telegram, карусели в Instagram; скоро Threads, Facebook. Бэкенд работает, раньше были платящие интересанты.",inter:"Подключается к L3, CityHub, Dine, Клиникам — автопостинг и контент.",link:null},
    promos:{t:"mini",layer:"UT",s:"dev",x:1132,y:98,label:"PromOS",cat:"Утилита · биржа дистрибуции",desc:"Биржа дистрибуции приложений: бизнес или частник скидывается на рекламу проекта от $5, получает личную ссылку и долю с каждого, кто по ней пришёл. Кошелёк создаётся сам, вход через Telegram без пароля. Прототип.",inter:"Приводит внешний трафик в любое приложение сети — L3-кейсы, игры, агрегаторы. Дополняет Loop со стороны привлечения.",pf:"promos",screens:4,links:[{label:"promos-tma.vercel.app",url:"https://promos-tma.vercel.app"}]},

    /* ——— MULTIMEDIA · трафик к пользователям ——— */
    news:{t:"mini",layer:"MM",s:"concept",x:120,y:810,label:"News",cat:"Мультимедиа · контент",desc:"Telegram-каналы: новости, подборки, обзоры; питают чаты.",inter:"Направляет аудиторию в L2-агрегаторы, продвигает L3-приложения, рекламирует игры; авто-публикация через LeadOS.",link:null},
    musichaed:{t:"mini",layer:"MM",s:"live",x:262,y:810,label:"MusicHAEd",cat:"Мультимедиа · вне петли",desc:"Музыкальный плеер. Отдельное приложение — приводит внешний трафик в экосистему.",inter:"Направляет трафик в L2-агрегаторы, рекомендует тематические L3-приложения (концерты, фестивали, Stage), может взаимодействовать с L1-агентами.",links:[{label:"musichaed.vercel.app",url:"https://musichaed.vercel.app"}]},
    social:{t:"mini",layer:"MM",s:"live",x:404,y:810,label:"Соцсети",cat:"Мультимедиа · бренд apphubstudio",desc:"Единый хэндл бренда — apphubstudio. Живые: Telegram-канал, Instagram, X, LinkedIn, Product Hunt. Заведены, но пусты: Threads, Facebook. Контент — брендбук v1.0 и дистрибуционный кит.",inter:"Внешний трафик на сайт, в Studio Bot и портфолио; позже — автопостинг через LeadOS.",links:[{label:"Telegram-канал",url:"https://t.me/AppHub_Studio"},{label:"Instagram",url:"https://www.instagram.com/apphubstudio/"},{label:"X",url:"https://x.com/Apphubstudio"},{label:"LinkedIn",url:"https://www.linkedin.com/company/apphubstudio/"},{label:"Product Hunt",url:"https://www.producthunt.com/@apphubstudio"}]},

    /* ——— GAMES · вовлечение ——— */
    crookedcook:{t:"mini",layer:"GAMES",s:"live",dom:"Еда",x:1058,y:772,label:"Crooked Cook",cat:"Игры · для HoReCa",desc:"Аркада-merge для гостей кафе и ресторанов: играешь, пока ждёшь заказ, бьёшь рекорд — получаешь промокод и возвращаешься в заведение.",inter:"Удержание в заведениях Dine; связана с Аркадами; вовлекает пользователей L1.",links:[{label:"@crooked_cook_bot",url:"https://t.me/crooked_cook_bot"}]},
    selfix:{t:"mini",layer:"GAMES",s:"live",x:1206,y:772,label:"Selfix",cat:"Игры · тест личности",desc:"Telegram-приложение: тест личности Big Five (OCEAN) с образными типами, PvP-дуэли и рейтинг.",inter:"Вовлекает пользователей L1; связан с Настолками; продвигается через News-каналы.",imgs:["/v2/shots/selfix-1.jpg","/v2/shots/selfix-2.jpg"],links:[{label:"Открыть Selfix",url:"https://masteroch.github.io/selfix/"}]},
    nardum:{t:"mini",layer:"GAMES",s:"live",x:1354,y:772,label:"NARDUM",cat:"Игры · длинные нарды",desc:"Длинные нарды в Telegram: партия против бота с подсказками коуча, школа тактик, вызов друга по ссылке, ранги и зал славы. Игра, где 60% — навык. Открыл в портфолио группу «Игры и развлечения».",inter:"Первая живая настолка сети: мультиплеер между пользователями L1, вызов друга — виральный вход. Кандидат на Loop-баллы за победы.",pf:"nardum",screens:6,links:[{label:"@nardum_game_bot",url:"https://t.me/nardum_game_bot"}]},
    arcades:{t:"mini",layer:"GAMES",s:"concept",x:1058,y:840,label:"Аркады",cat:"Игры · вовлечение",desc:"Аркадные игры для заведений и сети. Удержание и вовлечение: играешь — зарабатываешь Loop-баллы.",inter:"Подключены к Loop; связаны с Dine, Batumito, Tours, Shops; вовлекают пользователей L1.",link:null},
    boardgames:{t:"mini",layer:"GAMES",s:"live",x:1206,y:840,label:"Настолки",cat:"Игры · мультиплеер",pf:"nardum",desc:"Настольные игры: нарды (NARDUM — уже живой), шахматы и проще. Мультиплеер между пользователями.",inter:"Связаны с L1 — взаимодействие между пользователями; публикуются в чатах и каналах; ведут рекламный трафик на сервисы через L2.",links:[{label:"NARDUM",url:"https://t.me/nardum_game_bot"}]},

    /* ——— КЕЙСЫ · живые клиентские приложения из портфолио (правая колонка) ——— */
    ebit:{t:"case",layer:"L3",s:"live",dom:"Туризм",x:1650,y:60,label:"EBIT Expo 2026",cat:"Кейс · выставка · Батуми",desc:"Выставка гостеприимства в Батуми (4000+ гостей): каталог участников с фильтрами, карточки стендов с материалами и прайсом, программа по дням, QR-бейдж со сканером и ИИ-гид EBI по стендам и расписанию. Английский интерфейс.",inter:"Кейс направления Events. Стенды-рестораторы уходят в Dine, гости — в CityHub и Tours.",pf:"ebit",screens:5,links:[{label:"Открыть в Telegram",url:"https://t.me/expobatumibot/EBIT2026?startapp=home"}]},
    realtyforum:{t:"case",layer:"L3",s:"live",dom:"Недвижимость",x:1650,y:150,label:"Realty Forum",cat:"Кейс · форум · 2026",desc:"Форум недвижимости: QR-бейдж и нетворкинг, B2B-мэтчинг с ИИ, чаты, калькуляторы инвестора, микро-встречи. Админка организатора: KPI дня и ИИ-сводка, лента анонсов, сканирование бейджей, участники по тирам, аналитика.",inter:"Кейс направления Events на стыке с Realty: сводит застройщиков, брокеров и инвесторов.",pf:"realty-forum",screens:8,admin:{label:"Админка организатора",url:"https://realty-forum-admin-v3.vercel.app",pf:"realty-admin",screens:5},links:[{label:"realty-forum-tma.vercel.app",url:"https://realty-forum-tma.vercel.app"}]},
    bimboo:{t:"case",layer:"L3",s:"dev",dom:"Еда",x:1650,y:240,label:"Bimboo Land",cat:"Кейс · детские праздники",desc:"Детский праздник за три минуты: 24 программы, 70 героев, банкетный стол и смета, которая считается на лету. Демо.",inter:"Кейс на стыке Events и Dine: праздник + банкетный стол; персонажи — из каталога, смета — в один экран.",pf:"bimbooland",screens:7,links:[{label:"bimbooland.vercel.app",url:"https://bimbooland.vercel.app"}]},
    realtypreset:{t:"case",layer:"L3",s:"live",dom:"Недвижимость",x:1650,y:330,label:"Realty Preset",cat:"Кейс · продажа новостройки",desc:"Продажа новостройки в Telegram (Marea Residence): 3D-шахматка дома, статусы квартир, планировки, цены в USD/GEL, ход стройки, инженерия. Три языка.",inter:"Кейс Стройки/Realty: застройщик продаёт квартиры прямо в мессенджере; крупные расчёты — Crypto.",pf:"realty-preset",screens:5,links:[{label:"Открыть в Telegram",url:"https://t.me/RealtyPreset_AIbot?startapp=ref_mareaunitu502"}]},
    alliance:{t:"case",layer:"L3",s:"live",dom:"Недвижимость",x:1650,y:420,label:"Alliance",cat:"Кейс · жилой комплекс",desc:"Alliance Centropolis — презентация жилого комплекса: выбор формата квартиры, 3D-планировка и доходность, инфраструктура, ход стройки, инвест-условия, заявка на просмотр.",inter:"Кейс Стройки/Realty: инвест-презентация застройщика для L1-покупателей.",pf:"alliance",screens:6,links:[{label:"Открыть",url:"https://masteroch.github.io/alliance-centropolis/?v=5"}]},
    dolceeda:{t:"case",layer:"L3",s:"live",dom:"Еда",x:1650,y:510,label:"Dolce Eda",cat:"Кейс · кулинарный сервис",desc:"Кулинарный сервис в Telegram: подбор личного повара за пару вопросов, ИИ-помощник «Ишка», книга рецептов, профиль, уровни, топ поваров и челлендж недели.",inter:"Кейс Dine/WWC: повара — это L3-бизнесы внутри одного приложения; рецепты → продукты в Shops.",pf:"dolce-eda",screens:6,links:[{label:"Открыть в Telegram",url:"https://t.me/DolceEda_aiBot?startapp=8E41ADF7"},{label:"Веб-версия",url:"https://dolce-eda.vercel.app"}]},
    epoch:{t:"case",layer:"L3",s:"live",dom:"Еда",x:1650,y:600,label:"EPOCH",cat:"Кейс · ресторан · Батуми",desc:"Ресторан в Батуми: меню с фото и корзиной, промокод и чаевые, бронь стола по шагам, бронь события в банкетном зале, бонусные уровни и QR-карта гостя. Три языка. Панель управления: KPI смены в реальном времени, заказы по залу, подтверждение броней, редактор меню на 319 блюд.",inter:"Кейс Dine: собран на шаблоне-доноре; Loop и QR-карта гостя встроены.",pf:"epoch",screens:6,admin:{label:"Панель управления",url:"https://epoch-admin-seven.vercel.app",pf:"epoch-admin",screens:6},links:[{label:"epoch-client-lovat.vercel.app",url:"https://epoch-client-lovat.vercel.app"}]},
    neko:{t:"case",layer:"L3",s:"live",dom:"Еда",x:1650,y:690,label:"Neko Sushi",cat:"Кейс · суши-бар",desc:"Neko Sushi Bar — меню и бронь для суши-ресторана внутри Studio Bot. Живёт внутри Telegram; вне мессенджера отдаёт пустой экран (ждёт съёмки для портфолио).",inter:"Кейс Dine: первый живой ресторан на шаблоне; демо открывается из Studio Bot.",links:[{label:"Открыть в Telegram",url:"https://t.me/AppHub_Studio_Bot/neko"}]},
    postnicken:{t:"case",layer:"L3",s:"live",dom:"Туризм",x:1650,y:780,label:"Постникен",cat:"Кейс · усадьба · отель",desc:"Усадьба 1912 года под Калининградом: гостевой дом и А-Фреймы у воды, бани и чаны, номера и цены, визы гостей и история места. Хозяйская панель: заявки на визу, календарь занятости объектов, задачи команды, прайс.",inter:"Кейс Dine («Отели») и Tours: бронь жилья и услуг усадьбы.",pf:"postnicken",screens:7,admin:{label:"Хозяйская панель",url:"https://postnicken-admin.vercel.app",pf:"postnicken-admin",screens:6},links:[{label:"postnicken.vercel.app",url:"https://postnicken.vercel.app"}]},
    zemdoc:{t:"case",layer:"L3",s:"live",dom:"Здоровье",x:1840,y:60,label:"Земский Доктор",cat:"Кейс · медцентр",desc:"Медцентр: направления, онлайн-запись к врачу, услуги и цены, ИИ-регистратура dr.Zem.",inter:"Кейс направления Клиники: донор шаблона «медицина» для OS Builder.",pf:"zem-doc",screens:4,links:[{label:"Открыть в Telegram",url:"https://t.me/DrZem_AIbot?startapp=ref_213418325"},{label:"Веб-версия",url:"https://masteroch.github.io/zem-doc/"}]},
    antiage:{t:"case",layer:"L3",s:"live",dom:"Здоровье",x:1840,y:150,label:"AntiAge",cat:"Кейс · клиника антивозрастной медицины",desc:"Клиника антивозрастной медицины: 344 позиции прайса, запись с выбором врача и времени, 11 специалистов, результаты до и после, личный кабинет и документы. Кабинет клиники: выручка и средний чек, лента записей, база пациентов с LTV, автоподтверждение.",inter:"Кейс направления Клиники: спарсен с сайта клиента целиком (Парсер) — 344 позиции прайса без ручного ввода.",pf:"antiage",screens:6,admin:{label:"Кабинет клиники",url:"https://antiage-tma.vercel.app/admin",pf:"antiage-admin",screens:7},links:[{label:"antiage-tma.vercel.app",url:"https://antiage-tma.vercel.app"}]},
    megagym:{t:"case",layer:"L3",s:"dev",dom:"Здоровье",x:1840,y:240,label:"Mega Gym",cat:"Кейс · тренажёрный зал · Батуми",desc:"Тренажёрный зал в Батуми: клубная карта с QR на входе, 9 тарифов с посчитанной ценой одного дня, 25 тренеров с подбором по цели, расписание, три языка словами самого клуба. Плюс админка смены. Прототип.",inter:"Кейс фитнеса рядом с KING Fit; трафик из CityHub.",pf:"mega-gym",screens:6,link:null},
    anzhskin:{t:"case",layer:"L3",s:"live",dom:"Здоровье",x:1840,y:330,label:"ANZH Skin",cat:"Кейс · диагностика кожи",desc:"ANZH Skin Intelligence — диагностика кожи от врача-косметолога: 6 тестов и 40+ вопросов собираются в Skin Passport с типом кожи, персональной программой ухода и PDF-отчётом. Шесть языков.",inter:"Кейс ANZH: квиз-движок как вход в бьюти-экосистему; результат ведёт на запись и подбор средств.",pf:"anzh-skin",screens:6,links:[{label:"anzh-quiz.vercel.app",url:"https://anzh-quiz.vercel.app"}]},
    paratravel:{t:"case",layer:"L3",s:"live",dom:"Туризм",x:1840,y:420,label:"Paratravel",cat:"Кейс · клуб путешествий",desc:"Paratravel Club: главная с бонусным счётом, поиск и горящие туры, персональный подбор за 4 вопроса, клуб с уровнями и кэшбэком, мои поездки и чек-лист. Админка: ИИ-сводка по бизнесу, воронка сделок, задачи, календарь вылетов и оплат.",inter:"Кейс Tours: агентство продаёт туры и держит клуб лояльности в одном приложении.",pf:"paratravel-club",screens:5,admin:{label:"Админка клуба",url:"https://paratravel-admin-demo.vercel.app",pf:"paratravel-admin",screens:4},links:[{label:"paratravel-club.vercel.app",url:"https://paratravel-club.vercel.app"}]},
    tds:{t:"case",layer:"L3",s:"live",dom:"Ритейл",x:1840,y:510,label:"ТДС Мебель",cat:"Кейс · мебельный центр",desc:"Мебельный центр: соберите кухню и увидьте её в своей комнате по фото, магазин материалов, конструктор кухни, корзина, услуги собственного цеха. Админка: воронка заявок по этапам, очередь цеха раскроя, каталог на 3 201 позицию с выгрузкой с сайта.",inter:"Кейс Shops на стыке со Стройкой: каталог спарсен с сайта клиента целиком.",pf:"tds-mebel",screens:6,admin:{label:"Админка центра",url:"https://tds-mebel-admin.vercel.app",pf:"tds-mebel-admin",screens:6},links:[{label:"tds-mebel.vercel.app",url:"https://tds-mebel.vercel.app"}]},
    vodokanal:{t:"case",layer:"L3",s:"dev",dom:"Город и дом",x:1840,y:600,label:"Водоканал",cat:"Кейс · ЖКХ",desc:"ЖКХ в Telegram: статус по адресу и лента, показания счётчиков, оплата, каталог услуг, заявки, статус работ, чат-бот «Капелька». Прототип.",inter:"Кейс направления Дом и ЖКХ: городская служба как приложение без установки.",pf:"vodokanal",screens:3,links:[{label:"Открыть в Telegram",url:"https://t.me/Demo_App_AIbot/vodokanal?startapp=ref_213418325"},{label:"Веб-версия",url:"https://vodokanal-rho.vercel.app"}]},
    almare:{t:"case",layer:"L3",s:"dev",dom:"Город и дом",x:1840,y:690,label:"AL MARE",cat:"Кейс · жилой дом · Батуми",desc:"Приложение жилого дома на 217 соседей: пульс дома и заявки, взносы и платежи, заявки в УК, голосования, чат дома по темам, соседи (помощь и обмен), ИИ-консьерж «Альма». Прототип.",inter:"Кейс направления Дом и ЖКХ; соседи — готовая аудитория для CityHub и Loop.",pf:"almare",screens:6,links:[{label:"@almare_house_bot",url:"https://t.me/almare_house_bot"}]}
  },
  links: [
    /* студия → петля */
    ["site","studiobot"],["site","osbuilder"],["site","loop"],["site","l1"],["site","l3"],
    ["studiobot","linkos"],["studiobot","osbuilder"],["studiobot","dine"],["studiobot","portfolio"],
    ["linkos","osbuilder"],["linkos","l3"],["osbuilder","l3"],["osbuilder","l2"],["osbuilder","loop"],
    ["portfolio","l3"],
    /* ядро */
    ["l1","l2"],["l2","l3"],["l3","l1"],
    ["loop","l1"],["loop","l3"],["loop","l2"],["loop","cityhub"],["loop","epoch"],["loop","dine"],["loop","carrent"],
    /* L2 */
    ["l1","wwc"],["l1","korobka"],["l1","cityhub"],["l1","neon"],["l1","batumito"],["l1","bazapp"],["l1","realestate"],
    ["l2","wwc"],["l2","korobka"],["l2","cityhub"],["l2","neon"],["l2","batumito"],["l2","bazapp"],["l2","realestate"],
    /* L3 направления */
    ["l3","crypto"],["l3","events"],["l3","stage"],["l3","carrent"],["l3","tours"],["l3","dine"],["l3","shops"],["l3","construction"],["l3","anzh"],["l3","kingfit"],["l3","dropper"],["l3","med"],["l3","cityhome"],
    ["wwc","dine"],["wwc","shops"],["wwc","dolceeda"],
    ["cityhub","dine"],["cityhub","events"],["cityhub","tours"],["cityhub","carrent"],["cityhub","shops"],["cityhub","cityhome"],["cityhub","med"],
    ["neon","events"],["neon","tours"],["neon","carrent"],["neon","dine"],
    ["batumito","tours"],["batumito","carrent"],["batumito","dine"],["batumito","shops"],["batumito","events"],
    ["korobka","shops"],["korobka","crypto"],["realestate","korobka"],["realestate","tours"],["realestate","events"],["realestate","crypto"],["realestate","construction"],["realestate","dine"],
    ["construction","korobka"],["construction","crypto"],["construction","shops"],
    ["events","stage"],["events","tours"],["dine","events"],["dine","tours"],["carrent","tours"],
    ["bazapp","shops"],["bazapp","crypto"],["bazapp","dine"],
    ["anzh","dine"],["anzh","cityhub"],["anzh","crypto"],["anzh","neon"],
    ["kingfit","l1"],["kingfit","cityhub"],["kingfit","tours"],
    ["dropper","dine"],["dropper","shops"],["dropper","cityhub"],["dropper","neon"],["dropper","batumito"],
    ["cityhome","shops"],["cityhome","construction"],
    /* утилиты */
    ["editcmd","l3"],["editcmd","dine"],["leados","l3"],["leados","cityhub"],["leados","dine"],["leados","med"],["leados","news"],
    ["promos","l3"],["promos","l1"],["promos","nardum"],["promos","cityhub"],
    /* медиа */
    ["musichaed","l1"],["musichaed","l2"],["musichaed","stage"],["musichaed","events"],
    ["news","l1"],["news","l2"],["news","l3"],["news","arcades"],["news","boardgames"],
    ["social","site"],["social","studiobot"],["social","portfolio"],["social","l1"],
    /* игры */
    ["arcades","l1"],["arcades","dine"],["arcades","batumito"],["arcades","tours"],["arcades","shops"],["arcades","loop"],
    ["boardgames","l1"],["boardgames","l2"],["arcades","boardgames"],["boardgames","nardum"],
    ["crookedcook","dine"],["crookedcook","arcades"],["crookedcook","l1"],["crookedcook","neon"],
    ["selfix","l1"],["selfix","boardgames"],["selfix","news"],
    ["nardum","l1"],["nardum","loop"],
    /* кейсы → направления */
    ["ebit","events"],["ebit","dine"],["realtyforum","events"],["realtyforum","realestate"],["bimboo","events"],["bimboo","dine"],
    ["realtypreset","construction"],["realtypreset","realestate"],["alliance","construction"],["alliance","realestate"],
    ["dolceeda","dine"],["epoch","dine"],["neko","dine"],["neko","studiobot"],["postnicken","dine"],["postnicken","tours"],
    ["zemdoc","med"],["antiage","med"],["megagym","kingfit"],["megagym","cityhub"],["anzhskin","anzh"],
    ["paratravel","tours"],["tds","shops"],["tds","construction"],["vodokanal","cityhome"],["almare","cityhome"]
  ],
  zones: [
    {label:"APPHUB STUDIO",sub:"вход · сайт → визитка → конструктор → студия",x:260,y:-16,bx:40,by:-40,bw:440,bh:175,c:"#C5FF5F"},
    {label:"UTILITIES",sub:"вне петли · бесплатно → трафик",x:1130,y:-16,bx:980,by:-40,bw:300,bh:175,c:"#38bdf8"},
    {label:"MULTIMEDIA",sub:"вне петли · трафик к пользователям",x:260,y:752,bx:40,by:730,bw:440,bh:116,c:"#a78bfa"},
    {label:"ИГРЫ",sub:"аркады и настолки · вовлечение",x:1204,y:716,bx:974,by:700,bw:460,bh:168,c:"#fbbf24"},
    {label:"КЕЙСЫ · ЖИВЫЕ ПРИЛОЖЕНИЯ",sub:"клиентские продукты из портфолио · клик — экраны",x:1745,y:-16,bx:1560,by:-40,bw:370,bh:880,c:"#2dd4bf"}
  ]
};

/* ——— Совместная правка через общую базу (Supabase) ———
   ⚠ 2026-09-14: прежний проект ANZH Store (bsebatbejrhiabgsjhax) не резолвится (NXDOMAIN) — база недоступна.
   Карта работает от этого файла; редактор при недоступной базе сохраняет правки в браузере и один раз предупреждает.
   Чтобы вернуть общую базу: создай Supabase-проект → выполни src/supabase.sql → впиши url и anon-ключ ниже. Row для v2 = "v2". */
window.APPHUB_SYNC = {
  url:      "https://bsebatbejrhiabgsjhax.supabase.co",
  key:      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzZWJhdGJlanJoaWFiZ3NqaGF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MDMxOTMsImV4cCI6MjA5MDE3OTE5M30.KodqrjevcHK1sN3F4Hsq200TgGYlGhhAlmdCMtq32XQ",
  table:    "apphub_map",
  row:      "v2",
  writeKey: "AppHUB.Admin"   // правят базу те, кто открыл ссылку с ?key=AppHUB.Admin (регистр важен)
};
